name: resolve

on:
  push:
    branches:
      - "main"
      - "4.x-branch"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  resolve:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: swift package resolve
